# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  captcha_site_key: <%= ENV["CAPTCHA_SITE_KEY"] %>
  captcha_secret_key: <%= ENV["CAPTCHA_SECRET_KEY"] %>
  scale_base_url: <%= ENV["SCALE_BASE_URL"] %>
  scale_api_key: <%= ENV["SCALE_API_KEY"] %>
  scale_callback_key: <%= ENV["SCALE_CALLBACK_KEY"] %>
  base_url: <%= ENV["BASE_URL"] %>
  s3_bucket: <%= ENV["S3_BUCKET"] %>
  s3_access_key_id: <%= ENV["S3_ACCESS_KEY_ID"] %>
  s3_secret_access_key: <%= ENV["S3_SECRET_ACCESS_KEY"] %>
  s3_region: <%= ENV["S3_REGION"] %>

test:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  captcha_site_key: <%= ENV["CAPTCHA_SITE_KEY"] %>
  captcha_secret_key: <%= ENV["CAPTCHA_SECRET_KEY"] %>
  scale_base_url: <%= ENV["SCALE_BASE_URL"] %>
  scale_callback_key: <%= ENV["SCALE_CALLBACK_KEY"] %>
  scale_api_key: <%= ENV["SCALE_API_KEY"] %>
  base_url: <%= ENV["BASE_URL"] %>
  s3_bucket: <%= ENV["S3_BUCKET"] %>
  s3_access_key_id: <%= ENV["S3_ACCESS_KEY_ID"] %>
  s3_secret_access_key: <%= ENV["S3_SECRET_ACCESS_KEY"] %>
  s3_region: <%= ENV["S3_REGION"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  captcha_site_key: <%= ENV["CAPTCHA_SITE_KEY"] %>
  captcha_secret_key: <%= ENV["CAPTCHA_SECRET_KEY"] %>
  scale_base_url: <%= ENV["SCALE_BASE_URL"] %>
  scale_api_key: <%= ENV["SCALE_API_KEY"] %>
  scale_callback_key: <%= ENV["SCALE_CALLBACK_KEY"] %>
  base_url: <%= ENV["BASE_URL"] %>
  s3_bucket: <%= ENV["S3_BUCKET"] %>
  s3_access_key_id: <%= ENV["S3_ACCESS_KEY_ID"] %>
  s3_secret_access_key: <%= ENV["S3_SECRET_ACCESS_KEY"] %>
  s3_region: <%= ENV["S3_REGION"] %>
